# Generated by Django 4.0 on 2021-12-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='batan',
            field=models.CharField(default='some_string', max_length=1000),
        ),
    ]
