# Generated by Django 4.0 on 2021-12-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0002_video_batan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='icons',
        ),
    ]
