# Generated by Django 4.0 on 2021-12-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0003_remove_video_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='some_string', max_length=1000),
        ),
    ]
