# Generated by Django 3.2.9 on 2021-12-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0005_jacc_jacm_jacp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jacc',
            new_name='jaccs',
        ),
        migrations.RenameModel(
            old_name='jacm',
            new_name='jacms',
        ),
        migrations.RenameModel(
            old_name='jacp',
            new_name='jacps',
        ),
    ]
